# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-20 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=30)),
                ('creationTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, default='default', max_length=300, null=True)),
                ('place', models.CharField(blank=True, default='default', max_length=300, null=True)),
                ('creationTime', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.DateTimeField()),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Debate')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.DateTimeField()),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Created'), ('1', 'Started'), ('2', 'Finished'), ('-1', 'Cancelled')], default='0', max_length=30)),
                ('soundFile', models.FileField(blank=True, null=True, upload_to='soundFiles/')),
                ('duration', models.DurationField(blank=True, default=0, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('precision', 'Precision'), ('definition', 'Definition')], default='precision', max_length=30)),
                ('status', models.CharField(choices=[('0', 'Created'), ('1', 'Answered'), ('-1', 'Cancelled')], default='0', max_length=30)),
                ('creationTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Debate')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Participation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='leftParticipation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_left_participation', to='mainapp.Participation'),
        ),
        migrations.AddField(
            model_name='link',
            name='rightParticipation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_right_participation', to='mainapp.Participation'),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Debate'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Participation'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
