# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='linkType',
            field=models.CharField(blank=True, choices=[('0', 'Answer'), ('1', 'Question')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='linkedToPn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Participation'),
        ),
    ]
