# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170221_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='duration',
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('0', 'Created'), ('1', 'Started'), ('2', 'Finished'), ('next', 'Next'), ('-1', 'Cancelled')], default='0', max_length=30),
        ),
    ]
