# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170227_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreciation',
            name='debate',
        ),
        migrations.AlterField(
            model_name='participation',
            name='soundFile',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.Participation.upload_path),
        ),
    ]
