# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170405_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='jsonFile',
            field=models.FileField(blank=True, null=True, upload_to='jsonFile'),
        ),
    ]
